spring.application.name=AUTH-SERVICE
server.port=8070

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/userDb
spring.datasource.username=postgres
spring.datasource.password=12398765
spring.jpa.hibernate.ddl-auto=update
