spring.application.name=QUIZ-SERVICE
server.port=8090

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/quizDb
spring.datasource.username=postgres
spring.datasource.password=12398765
spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=http://localhost:8761/eureka