spring.application.name=Api-Gateway
server.port=8765

#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true


spring.cloud.gateway.routes[0].id=question-service
spring.cloud.gateway.routes[0].uri=lb://QUESTION-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/questions/**

spring.cloud.gateway.routes[1].id=quiz-service
spring.cloud.gateway.routes[1].uri=lb://QUIZ-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/quiz/**

spring.cloud.gateway.routes[2].id=Auth-Service
spring.cloud.gateway.routes[2].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedCredentials=true

